#!/usr/bin/python
# =============================================================================
# Module: xcorder
# Contacts: Edward Li (drawdeil@gmail.com)
# =============================================================================
"""__DESC__

"""

# =============================================================================
# IMPORTS
# =============================================================================
import os
import sys
from PyQt4 import QtGui
from gui import Gui

# =============================================================================
# PUBLIC FUNCTIONS
# =============================================================================
def main():

    app = QtGui.QApplication(sys.argv)
    app.setApplicationName('xcorder')

    scriptDir = os.path.dirname(os.path.realpath(__file__))
    with open(os.path.join(scriptDir ,'stylesheet.qss'), 'r') as file_:
        app.setStyleSheet(file_.read())

    gui = Gui()
    gui.show()

    sys.exit(app.exec_())

# =============================================================================

if __name__ == '__main__':
    main()

# =============================================================================

